// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: picam.proto

package picam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PiCamClient is the client API for PiCam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PiCamClient interface {
	// SendImage, sends an image from the client to the server.
	SendImage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type piCamClient struct {
	cc grpc.ClientConnInterface
}

func NewPiCamClient(cc grpc.ClientConnInterface) PiCamClient {
	return &piCamClient{cc}
}

func (c *piCamClient) SendImage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/picam.proto.PiCam/SendImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PiCamServer is the server API for PiCam service.
// All implementations must embed UnimplementedPiCamServer
// for forward compatibility
type PiCamServer interface {
	// SendImage, sends an image from the client to the server.
	SendImage(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPiCamServer()
}

// UnimplementedPiCamServer must be embedded to have forward compatible implementations.
type UnimplementedPiCamServer struct {
}

func (UnimplementedPiCamServer) SendImage(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendImage not implemented")
}
func (UnimplementedPiCamServer) mustEmbedUnimplementedPiCamServer() {}

// UnsafePiCamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PiCamServer will
// result in compilation errors.
type UnsafePiCamServer interface {
	mustEmbedUnimplementedPiCamServer()
}

func RegisterPiCamServer(s grpc.ServiceRegistrar, srv PiCamServer) {
	s.RegisterService(&PiCam_ServiceDesc, srv)
}

func _PiCam_SendImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiCamServer).SendImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/picam.proto.PiCam/SendImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiCamServer).SendImage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PiCam_ServiceDesc is the grpc.ServiceDesc for PiCam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PiCam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "picam.proto.PiCam",
	HandlerType: (*PiCamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendImage",
			Handler:    _PiCam_SendImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picam.proto",
}
